### PR TITLE
Add blinky for the M0S Dock

### PR DESCRIPTION
**Pull request by brainstorm**
As mentioned in https://github.com/sipeed/M0S_BL616_example/issues/2

### CODE REVIEW

**Comment by sakumisu** [comment]
Put this in your own repo.

**Comment by sakumisu** [comment]
This binds the board, it is not right. Helloworld demo is for all chips.

**Comment by brainstorm** [comment]
> This binds the board, it is not right. Helloworld demo is for all chips.

I expected this comment, is there any #ifdef/conditional code for the different boards?

**Comment by sakumisu** [comment]
In board_init

**Pull request closed without merging**
