### PR TITLE
cmake: handle STREQUAL when variable is not defined

### PR DESCRIPTION
**Pull request by cooldome**
When I try to compile any example using cmake from the official sdk download from https://dev.bouffalolab.com, 
I am getting this error:
```
CMake Error at tools/cmake/compiler_flags.cmake:12 (if):
  if given arguments:

    "STREQUAL" "y"

  Unknown arguments specified
Call Stack (most recent call first):
  CMakeLists.txt:4 (include)
```
This issue is well described here https://stackoverflow.com/questions/39707772/cmake-error-if-given-arguments-followed-by-parenthesis-not-equals-and-si/39733128 and good workarounds are given.

IMO, this issue is fixed in more recent versions of cmake, but I want it to work with cmake provided with gcc on https://dev.bouffalolab.com

### CODE REVIEW

**Comment by sakumisu** [comment]
this will not casue error,you can update your cmake for a try

**Comment by cooldome** [comment]
Updating cmake should work as well. The intention is to make it work with cmake in https://dev.bouffalolab.com/media/upload/download/BouffaloLab_eclipse_x86_64_win.zip.
Because this is how you get official gcc-riscv, openocd, cmake from the vendor.

It is BouffaloLab who needs to update its cmake in sdk it provides to clients.
Another option is to accept this PR.

**Comment by sakumisue** [comment]
cmake tool in eclipse comes from cmake org,not us.We just make it for clients easier to use so that they do not download from others.

**Comment by sakumisu** [comment]
cmake tool in eclipse comes from cmake org,not us.We just make it for clients easier to use so that they do not download from others.I think your problem is not the string error,cmake makes it the same.

**Pull request merged**
